### ISSUE TITLE
Day of Week

### ISSUE THREAD

**Issue by ArsalanRiaz** [dsi-principles-prog/midterm-ArsalanRiaz#1]
There is a "Date" column in the data set. Since which day the fight is occurring is important, therefore, we need to extract the day of the week from the date column. 

This will not only help us to identify the importance of the fight but it will make our machine learning algorithm faster.

The best approach is you can simply split the date into different columns by year, month and day of the week.
Expected Result after splitting the date column
Year          2019  
Month       01  
Day             06
              

Write a function to extract the day of the week. Test is with assert and then by pipeline include it in the 40 - modelling  and select it for the final modelling

**Comment by qianyisun** [comment]
added Day_of_Week feature, closes #1


You can see my Day_of_Week function code in the 30-feature-engineering. At the same time, I use  the assert to test  the function in the 40-modeling.

**Comment by qianyisun** [comment]
added Day_of_Week feature, closes #1

You can see my Day_of_Week function code in the 30-feature-engineering. At the same time, I use the assert to test the function in the 40-modeling.
